### ISSUE TITLE
Z.EntityFramework.Plus.EFCore Cast error

### ISSUE THREAD

**Issue by bobgodfrey** [hoagsie/BetterEntityFramework#1]
I did not make any modifications to your sample but on line 27 I am getting the following cast error from Z.EntityFramework.Plus.EFCore

Line 27:  data.Service.Category.UpdateWhere(category => category.Publish == false, category => new Category { Publish = true }).Wait();

"Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryContextFactory' to type 'Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory'."}

**Comment by hoagsie** [comment]
This makes sense as an update where operation does not make sense against an in-memory store. It's not SQL Server at this point. As I stated in my article, this code is not a "working" sample per se but a mix of recipes to demonstrate how code can be organized. I have tested the features individually. However, the mashup in Program.cs has not been. It's up to you to make what you want work for your needs.
